### PR TITLE
Type `last` is documented

### PR DESCRIPTION
**Pull request by gretelliz**
Type `last` is documented in CHANGELOG.rst

### CODE REVIEW

**Review by viniarck — COMMENTED** [review]
@gretelliz nicely done. 

Can you document in the openapi.yml spec too? The `last` type value isn't there yet, and only some values are mentioned in the descrition.  Maybe instead of keeping the docs in the "description" of "last" we could actually specify it as [enum string](https://swagger.io/docs/specification/data-models/enums/). In the description, maybe we can keep additional information if needed more context. But then when someone implements a front-end they'll have all the information needed.

**Comment by gretelliz** [comment]
Done in PR #92

**Comment by viniarck** [comment]
Nicely done @gretelliz, let's close this issue here then.

**Comment by viniarck** [comment]
Oops, I ended up closing this PR, let me open it again. Although the fix was done on PR #92, the changelog.rst updates here are still worth merging, right @gretelliz ?

**Review by viniarck — APPROVED** [review]

**Comment by gretelliz** [comment]
Right!

**Pull request merged**
