### PR TITLE
Check for `instructions` in `match_and_apply`

### LINKED ISSUE #103: `sdntrace_cp` isn't supporting `instructions` yet
`sdntrace_cp` relies on `flow_manager`'s `stored_flows`, which supports [both `actions` and `instructions` in the flow DB document](https://github.com/kytos-ng/flow_manager/blob/master/db/models/__init__.py#L116-L117). `actions` was historically to support OF1.0, and `instructinos` is for OF1.3. 

When trying to perform a match, `sdntrace_cp` should work with both too, `actions` and `instructions` are mutually exclusive per flow though:

https://github.com/kytos-ng/sdntrace_cp/blob/master/main.py#L259-L260

#### Example

If you use a ring topology with hosts between port 1 and 2 on sw1, and then push a flow to forward between port 1 and 2:

```
❯ curl -X POST http://127.0.0.1:8181/api/kytos/flow_manager/v2/flows/ -H 'Content-type: application/json' -d '{ "force": false, "flows": [ { "priority": 2000, "match": { "in_port": 1 }, 
"instructions": [ { "instruction_type": "apply_actions", "actions": [ { "action_type": "output", "port": 2 } ] } ] }, { "priority": 2000, "match": { "in_port": 2 }, "instructions": [ { "
instruction_type": "apply_actions", "actions": [ { "action_type": "output", "port": 1 } ] } ] } ] }'
{"response":"FlowMod Messages Sent"}
```
ping will work:
```
64 bytes from 10.0.0.4: icmp_seq=60 ttl=64 time=0.070 ms
64 bytes from 10.0.0.4: icmp_seq=61 ttl=64 time=0.147 ms
64 bytes from 10.0.0.4: icmp_seq=62 ttl=64 time=0.144 ms
64 bytes from 10.0.0.4: icmp_seq=63 ttl=64 time=0.159 ms
```

- `sdntrace_cp` will fail. `instructions` will be used by `telemetry_int` (so the priority of this bug might increase depending how we'll go about the consistency check), and any other existing NApp could already be using `instructions`, so this is actually a bug, it hasn't surfaced before yet since NApps are using primarily the historical `actions` format:

```
❯ curl -H 'Content-type: application/json' -X PUT http://127.0.0.1:8181/api/amlight/sdntrace_cp/v1/trace -d '{"trace": {"switch": {"dpid": "00:00:00:00:00:00:00:01", "in_port": 1}}}' 
{"result":[{"dpid":"00:00:00:00:00:00:00:01","port":1,"time":"2023-07-25 16:29:32.466822","type":"incomplete","out":null}]}
```

### PR DESCRIPTION
**Pull request by gretelliz**
Closes #103 

### Summary

This is to support `instructions` in `sdntrace_cp` when performing a match.

### Local Test

Same example in issue:

```
{"result":[{"dpid":"00:00:00:00:00:00:00:01","port":1,"time":"2023-08-03 12:21:42.515496","type":"starting"},{"dpid":"00:00:00:00:00:00:00:02","port":2,"time":"2023-08-03 12:21:42.515556","type":"last","vlan":2,"out":{"port":1}}]}
```
### End-to-end Test

[See PR](https://github.com/kytos-ng/kytos-end-to-end-tests/pull/254)

### CODE REVIEW

**Review by viniarck — COMMENTED** [review]
Excellent to have `instructions` supported, @gretelliz.

1 - For the unit test can you also add a case where the instruction wouldn't match or wouldn't have an outgoing port?
2 - Related to this PR, if you could also add an e2e test pushing flows with instruction that'd be great, typically we rely on mef_eline but since `mef_eline` is still using `actions` directly, then maybe using a simple topology where it would have connectivity between two hosts (similar to the approach when back then you had to create flows directly on flow_manager to be able to trace with untagged/any vlan when mef_eline wasn't supporting it yet).

**Review by viniarck — APPROVED** [review]
Leaving it pre-approved. 

Let's only merge this once `2023.1` is released (and tagged) and when the e2e test is also addressed though since we're in code freeze, OK? 

Thanks, Gretel.

**Comment by viniarck** [comment]
@gretelliz `2023.1` has been tagged, when you have a chance, please solve the git conflicts and make sure the e2e related to this part is still passing and then feel free to merge it. In the changelog, it should be in the unreleased section since this will be for `2023.2`, OK?

**Review by viniarck — APPROVED** [review]
LGTM. Feel free to merge if e2e related to this part is still passing, thanks, Gretel.

**Comment by gretelliz** [comment]
@viniarck, thank You!

**Pull request merged**
